import TableUser from '@/components/People/TableUser';
import { ROLE_TYPE } from '@/src/interfaces/auth/auth.interface';
import { withTranslationsProps } from '@/src/next/with-app';
import Head from 'next/head';

const EditorManagement = () => {
	return (
		<>
			<Head>
				<title>Editor management</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<TableUser role={ROLE_TYPE.EDITOR} />
		</>
	);
};

export async function getServerSideProps(ctx) {
  return await withTranslationsProps(ctx)
}

export default EditorManagement;
