import EmailInformationTab from '@/components/Settings/Email/EmailInformation';
import EmailTemplates from '@/components/Settings/Email/EmailTemplates';
import MailLogs from '@/components/Settings/Email/MailLogs';
import DashboardRoute from '@/components/routes/DashboardRoute';
import { withTranslationsProps } from '@/src/next/with-app';
import { useQuery } from '@/hooks/useQuery';
import { IGetSubdomainSettingsResponse } from '@/src/interfaces/settings/settings.interfaces';
import { getSubdomainSettings } from '@/src/services/settings/apiSettings';
import { Tabs } from 'antd';
import Head from 'next/head';
import { useState } from 'react';
import { toast } from 'react-toastify';
import { useTranslation } from 'next-i18next';

const EmailSettingPage = () => {
	const { t } = useTranslation()
	const [subdomainSetting, setSubdomainSetting] = useState<IGetSubdomainSettingsResponse>(null)
	/* -------------------------- GET SUBDOMAIN SETTING ------------------------- */

	useQuery(
		['IGetSubDomainResponse'],
		() => getSubdomainSettings(),
		{
			onSuccess: (res) => {
				setSubdomainSetting(res.data)
			},
			onError: (err) => {
				toast.error(err.data?.message);
			}
		}
	);

	return (
		<>
			<Head>
				<title>Email Setting</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<DashboardRoute>
				<div className="settings-email-tab -tw-mt-8">
					<Tabs
						defaultActiveKey="1"
						onChange={() => null}
						items={[
							{
								label: t('dashboard.label.email_information'),
								key: '1',
								children: <EmailInformationTab data={subdomainSetting} />,
							},
							{
								label: t('dashboard.label.email_templates'),
								key: '2',
								children: <EmailTemplates />,
							},
							{
								label: t('dashboard.label.mail_logs'),
								key: '3',
								children: <MailLogs />,
							},
						]}
					/>
				</div>
			</DashboardRoute>
		</>
	);
};

export async function getServerSideProps(ctx) {
  return await withTranslationsProps(ctx)
}

export default EmailSettingPage;
