import DashboardRoute from '@/components/routes/DashboardRoute';
import { withTranslationsProps } from '@/src/next/with-app';
import { Col, Form, Input, Row } from 'antd';
import Head from 'next/head';

const SubscriptionsSettings = () => {
	const onSubmit = (data) => {
		console.log(data);
	};

	return (
		<DashboardRoute>
			<Head>
				<title>Subscription Settings</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<div>
				<div className="tw-text-3xl tw-font-semibold tw-mb-10">Settings</div>
				<Form id="addSubscriptionCoupon" onFinish={onSubmit} layout="vertical">
					<Row>
						<Col span={8}>
							<Form.Item
								name="remindDays"
								label="Remind before (days)"
								rules={[
									{
										required: true,
									},
								]}
							>
								<Input placeholder="Enter usage limit" />
								<div className="tw-opacity-50">
									Specify how many days you want to remind your customers about subscription expiration. (Via mail)
								</div>
							</Form.Item>
						</Col>
					</Row>
				</Form>
			</div>
		</DashboardRoute>
	);
};

export async function getServerSideProps(ctx) {
  return await withTranslationsProps(ctx)
}

export default SubscriptionsSettings;
