import Head from 'next/head';
import PriceArea from '../../../components/v2/PriceArea';
import DefaultLayout from '../../layouts';
import { withTranslationsProps } from '../../next/with-app';

function Price() {
  return (
    <>
      <Head>
        <title>Get ready to learn and converse</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <DefaultLayout>
        <PriceArea step={1} />
      </DefaultLayout>
    </>
  )
}

export async function getServerSideProps(ctx) {
  return await withTranslationsProps(ctx)
}

export default Price