import Head from 'next/head';
import PriceArea from '../../../components/v2/PriceArea';
import BreadCrumb from '../../../components/common/BreadCrumb';
import DefaultLayout from '../../layouts';
import { withTranslationsProps } from '../../next/with-app';

function PriceRegister() {
  return (
    <>
      <Head>
        <title>Get ready to learn and converse</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <DefaultLayout>
        <>
          <BreadCrumb title="Get ready to learn and converse" />
          <PriceArea step={2} />
        </>
      </DefaultLayout>
    </>
  )
}

export async function getServerSideProps(ctx) {
  return await withTranslationsProps(ctx)
}

export default PriceRegister