import TableRole from '@/components/People/TableRole';
import DashboardRoute from '@/components/routes/DashboardRoute';
import { useQuery } from '@/hooks/useQuery';
import { IListRoleManagementResponse } from '@/src/interfaces/people/people.interface';
import { withTranslationsProps } from '@/src/next/with-app';
import { getListRoleManagement } from '@/src/services/people/apiPeople';
import Head from 'next/head';
import { useState } from 'react';
import { toast } from 'react-toastify';

const RoleManagement = () => {
	/* ------------------------ GET LIST ROLE MANAGEMENT ------------------------ */
	const [listRoleManagement, setListRoleManagement] = useState<IListRoleManagementResponse[]>([]);
	const getRoleManagementQuery = useQuery<IListRoleManagementResponse[]>(
		['IGetRoleManagementsRequest'],
		() => getListRoleManagement(),
		{
			onSuccess: (res) => {
				setListRoleManagement(res.data);
			},
			onError: (err) => {
				toast.error(err.data?.message);
			},
		}
	);

	return (
		<>
			<Head>
				<title>Role management</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<DashboardRoute>
				<TableRole
					data={listRoleManagement}
					loading={getRoleManagementQuery.isFetching}
					refetch={getRoleManagementQuery.refetch}
				/>
			</DashboardRoute>
		</>
	);
};

export async function getServerSideProps(ctx) {
  return await withTranslationsProps(ctx)
}

export default RoleManagement;
