import DashboardRoute from '@/components/routes/DashboardRoute';
import { RouterConstants } from '@/constants/router';
import { Tabs } from 'antd';
import Head from 'next/head';
import { useRouter } from 'next/router';

enum TutorInvoicesTab {
	Accounts = 'accounts',
	Invoices = 'invoices',
}

const TutorInvoicesLayout = ({ children }) => {
	const router = useRouter();
	const onSwitchTab = (key: TutorInvoicesTab) => {
		switch (key) {
			case TutorInvoicesTab.Accounts:
				router.push(RouterConstants.DASHBOARD_TUTOR_MATCH_INVOICES_ACCOUNTS.path);
				break;
			case TutorInvoicesTab.Invoices:
				router.push(RouterConstants.DASHBOARD_TUTOR_MATCH_INVOICES_INVOICES.path);
				break;
			default:
				break;
		}
	};
	return (
		<>
			<Head>
				<title>Tutor Invoices</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<DashboardRoute>
				<div className="tutor-class-tab -tw-mt-8">
					<Tabs defaultActiveKey={router.asPath.split('/').pop()} onChange={(e: TutorInvoicesTab) => onSwitchTab(e)}>
						<Tabs.TabPane tab="Accounts" key={TutorInvoicesTab.Accounts} />
						<Tabs.TabPane tab="Invoices" key={TutorInvoicesTab.Invoices} />
					</Tabs>
					{children}
				</div>
			</DashboardRoute>
		</>
	);
};

export default TutorInvoicesLayout;
