import DashboardRoute from '@/components/routes/DashboardRoute';
import { RouterConstants } from '@/constants/router';
import { userStore } from '@/src/stores/users/users.store';
import { Tabs } from 'antd';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';

enum TutorClassesTab {
	PLANS = 'plans',
	CLASSES = 'classes',
	CALENDAR = 'calendar',
}

const TutorClassesLayout = ({ children }) => {
	const router = useRouter();
	const [currentTab, setCurrentTab] = useState<string>(TutorClassesTab.PLANS);
	const onSwitchTab = (key: TutorClassesTab) => {
		switch (key) {
			case TutorClassesTab.PLANS:
				router.push(RouterConstants.DASHBOARD_TUTOR_MATCH_CLASSES_PLANS.path);
				break;
			case TutorClassesTab.CLASSES:
				router.push(RouterConstants.DASHBOARD_TUTOR_MATCH_CLASSES_CLASSES.path);
				break;
			case TutorClassesTab.CALENDAR:
				router.push(RouterConstants.DASHBOARD_TUTOR_MATCH_CLASSES_CALENDAR.path);
				break;
			default:
				break;
		}
	};

	useEffect(() => {
		if(router.asPath.includes('/classes/classes')){
			setCurrentTab(TutorClassesTab.CLASSES);
		} else if (router.asPath.includes('/classes/plans')){
			setCurrentTab(TutorClassesTab.PLANS);
		} else if (router.asPath.includes('/classes/calendar')){
			setCurrentTab(TutorClassesTab.CALENDAR);
		}
	}, [])
	
	return (
		<>
			<Head>
				<title>Tutor classes</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<DashboardRoute>
				<div className="tutor-class-tab -tw-mt-8">
					<Tabs activeKey={currentTab} onChange={(e: TutorClassesTab) => onSwitchTab(e)}>
						{userStore.currentUser && userStore.currentUser.role !== 'STUDENT' && <Tabs.TabPane tab="Plans" key={TutorClassesTab.PLANS} />}
						<Tabs.TabPane tab="Classes" key={TutorClassesTab.CLASSES} />
						<Tabs.TabPane tab="Calendar" key={TutorClassesTab.CALENDAR} />
					</Tabs>
					{children}
				</div>
			</DashboardRoute>
		</>
	);
};

export default TutorClassesLayout;
