import CustomTable from '@/components/common/CustomTable';
import HeaderTable from '@/components/common/HeaderTable';
import DashboardRoute from '@/components/routes/DashboardRoute';
import { PAGE_SIZE } from '@/constants';
import { RouterConstants } from '@/constants/router';
import { useMutation } from '@/hooks/useMutation';
import { useQuery } from '@/hooks/useQuery';
import { ICommonSearchRequest, Option } from '@/src/interfaces/common/common.interface';
import { IFAQsTable, IGetFAQResponse } from '@/src/interfaces/faqManagement/faqManagement.interface';
import { IHeaderTable } from '@/src/interfaces/mydrive/mydrive.interface';
import { withTranslationsProps } from '@/src/next/with-app';
import { deleteFAQById, getFAQ } from '@/src/services/faqManagement/apiFAQManagement';
import { DeleteOutlined, EditOutlined } from '@ant-design/icons';
import { Button, Form, Pagination } from 'antd';
import dayjs from 'dayjs';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useState } from 'react';
import { useTranslation } from 'next-i18next';
import { toast } from 'react-toastify';

const FAQs = () => {
	const { t } = useTranslation()
	const router = useRouter();
	const [currentPage, setCurrentPage] = useState(1);
	const [formSearch] = Form.useForm<ICommonSearchRequest>();

	const searchFAQOptions: Option<keyof any>[] = [
		{
			value: 'title',
			label: t('dashboard.option.title'),
		},
		{
			value: 'category',
			label: t('dashboard.option.category'),
		},
	];

	const columns: IHeaderTable<IFAQsTable & { tools: string }>[] = [
		{
			label: t('dashboard.option.title'),
			key: 'title',
			widthGrid: '1fr',
		},
		{
			label: t('dashboard.option.category'),
			key: 'category',
			widthGrid: '1fr',
		},
		{
			label: t('dashboard.option.published_date'),
			key: 'publishedAt',
			widthGrid: '1fr',
		},
		{
			label: t('dashboard.option.actions'),
			key: 'tools',
			widthGrid: '1fr',
		},
	];

	/* ---------------------------- GET LIST OF BLOGS --------------------------- */
	const [listOfFAQs, setListOfFAQs] = useState<IGetFAQResponse>({
		total: 0,
		data: [],
	});
	const [searchKey, setSearchKey] = useState<string>('');
	const getListOfFAQsQuery = useQuery<any>(
		['IGetFAQResponse', currentPage],
		() =>
			getFAQ({
				take: PAGE_SIZE,
				skip: PAGE_SIZE * (currentPage - 1),
			}),
		{
			onSuccess: (res) => {
				setListOfFAQs({ total: 100, data: res.data.filter((x) => !x.isDeleted) });
			},
			onError: (err) => {
				toast.error(err.data?.message);
			},
		}
	);

	/* ------------------------------- DELETE FAQ ------------------------------- */
	const onDeleteFAQCategoryMutation = useMutation<any, string>(deleteFAQById, {
		onSuccess: (res) => {
			toast.success(t('dashboard.notification.delete_faq_success'));
			getListOfFAQsQuery.refetch();
		},
		onError: (err) => {
			toast.error(t('dashboard.notification.delete_faq_error'));
		},
	});

	return (
		<DashboardRoute>
			<Head>
				<title>FAQ Management</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<HeaderTable
				tableName={t('dashboard.title.FAQs')}
				form={formSearch}
				searchOptions={searchFAQOptions}
				onAdd={() => router.push(RouterConstants.DASHBOARD_FAQ_MANAGEMENT_FAQS_ADD_FAQ.path)}
				onGetSearchKey={(searchKey) => {}}
			/>
			<CustomTable
				className="border-theme-6 tw-border tw-border-solid tw-shadow-lg tw-rounded-b-xl"
				columns={columns}
				isLoading={false}
				data={listOfFAQs.data.map((item) => ({
					title: item.question,
					category: item.category.name,
					publishedAt: dayjs(item.createdAt).format('DD/MM/YYYY'),
					tools: (
						<div className="tw-flex tw-items-center tw-gap-1">
							<Button
								icon={
									<EditOutlined
										style={{
											fontSize: 16,
										}}
									/>
								}
								className="bg-theme-4 color-theme-7 !tw-border-none"
								onClick={() => router.push(`faqs/${item.id}`)}
							/>
							<Button
								icon={
									<DeleteOutlined
										style={{
											fontSize: 16,
										}}
									/>
								}
								className="!tw-bg-deleteIconDavid color-theme-7 !tw-border-none"
								onClick={() => onDeleteFAQCategoryMutation.mutate(item.id)}
							/>
						</div>
					),
				}))}
			/>
			<Pagination
				className="!tw-mt-6 tw-flex tw-justify-end"
				total={listOfFAQs.total}
				pageSize={PAGE_SIZE}
				current={1}
				onChange={(page: number) => {
					setCurrentPage(page);
				}}
			/>
		</DashboardRoute>
	);
};

export async function getServerSideProps(ctx) {
  return await withTranslationsProps(ctx)
}

export default FAQs;
