import FormAddUpdateBanner from '@/components/BannerManagement/FormAddUpdateBanner';
import { withTranslationsProps } from '@/src/next/with-app';
import Head from 'next/head';

const AddBanner = () => {
	return (
		<>
			<Head>
				<title>Add || Banner management</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<FormAddUpdateBanner />
		</>
	);
};

export async function getServerSideProps(ctx) {
  return await withTranslationsProps(ctx)
}

export default AddBanner;
