import { Tabs } from 'antd';
import Head from 'next/head';
import { useState } from 'react';
import TeacherRegisterForm from '../../../../components/TeachRegister/TeacherRegisterForm';
import BookWithTeacherArea from '../../../../components/v2/BookWithTeacher/BookWithTeacherArea';
import DefaultLayout from '../../../layouts';
import { withTranslationsProps } from '../../../next/with-app';

function Tools() {
  const [active, setActive] = useState('tutors');

  return (
    <>
      <Head>
        <title>Engage one-on-one with native or local tutors</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <DefaultLayout>
        <>
          <div className="teach__page">
            <div className="feature-wrapper">
              <div className="feature-tabs">
                <div className="container">
                  <Tabs activeKey={active} onChange={(key) => setActive(key)}>
                    <Tabs.TabPane tab="Tutors" key="tutors" />
                    <Tabs.TabPane disabled tab="Bookings" key="bookings" />
                    <Tabs.TabPane disabled tab="Calendar" key="calendar" />
                    <Tabs.TabPane disabled tab="Message" key="message" />
                    <Tabs.TabPane disabled tab="Credits" key="credits" />
                  </Tabs>
                </div>
              </div>

              {
                {
                  "tutors": (
                    <div className='tw-py-10 tw-px-0'>
                      <BookWithTeacherArea />
                      <section className="breadcrumb-teacher-register-section">
                        <TeacherRegisterForm
                          title="Register an account to provide 1-on-1 instruction and earn more income"
                          description="You can choose from a variety of pre-made content in the course library, and our system allows tutors to create more materials for the tutoring session."
                        />
                      </section>
                    </div>
                  ),
                }[active] || null
              }
            </div>
          </div>
        </>
      </DefaultLayout>
    </>
  )
}

export async function getServerSideProps(ctx) {
  return await withTranslationsProps(ctx)
}

export default Tools